// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type AccountMaster struct {
	AccountID   int32
	AccountName string
}

type OfferList struct {
	OfferID   int32
	AccountID sql.NullInt32
}
