// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type AccountMaster struct {
	AccountID   string
	AccountName string
}

type OfferList struct {
	OfferID   string
	AccountID string
}
