// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"
)

const getAccountMaster = `-- name: GetAccountMaster :one
SELECT account_id, account_name FROM account_master
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetAccountMaster(ctx context.Context, accountID string) (AccountMaster, error) {
	row := q.db.QueryRowContext(ctx, getAccountMaster, accountID)
	var i AccountMaster
	err := row.Scan(&i.AccountID, &i.AccountName)
	return i, err
}

const getOfferList = `-- name: GetOfferList :one
SELECT offer_id, account_id FROM offer_list
WHERE offer_id = $1 LIMIT 1
`

func (q *Queries) GetOfferList(ctx context.Context, offerID string) (OfferList, error) {
	row := q.db.QueryRowContext(ctx, getOfferList, offerID)
	var i OfferList
	err := row.Scan(&i.OfferID, &i.AccountID)
	return i, err
}
